language: python
python:
  - "3.6"

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/build/zachdlang/flasktools

install:
  - pip install -r requirements.txt
  - pip install pytest

jobs:
  include:
    - stage: build
      script: ./.travis/install-flasktools.sh
    - stage: test
      script: ./.travis/create-test-config.sh && pytest
